
CXX_FLAGS=-g -Wall -Wextra -pedantic

CXX_INC=-I../include

CXX=g++ -std=c++17

CXX_CC=$(CXX) $(CXX_FLAGS) $(CXX_INC)

all:
	$(CXX_CC) -o basic-switch basic-switch.cpp
	$(CXX_CC) -o nodefault-switch nodefault-switch.cpp
	$(CXX_CC) -o user-defined-switch user-defined-switch.cpp
